[tool.poetry]
name = "nonebot-plugin-groupmate-waifu"
version = "1.3.4"
description = ""
authors = ["KarisAya <1048827424@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12,<3.13"
nonebot2 = "^2.1.2"
nonebot-adapter-onebot = "^2.3.1"
httpx = "^0.25.1"
pil-utils = "^0.1.8"
nonebot-plugin-apscheduler = "^0.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
