[tool.poetry]
name = "nonebot-plugin-groupmate-waifu"
version = "1.4.1"
description = ""
authors = ["KarisAya <1048827424@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nonebot-plugin-clovers = {extras = ["nonebot"], version = "^0.1.4"}
clovers-groupmate-waifu = "^0.1.0.post3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
